/**
 * \file
 *
 * \brief Plot widget demo application
 *
 * Copyright (C) 2011 Atmel Corporation. All rights reserved.
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 * Atmel AVR product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#include <led.h>
#include <board.h>
#include <string.h>

#include <gfx/gfx.h>
#include <gfx/win.h>
#include <gfx/wtk.h>
#include <gfx/sysfont.h>
#include <membag.h>
#include <debug.h>
#include <mainloop.h>
#include <string.h>
#include <stream.h>

#include "app_widget.h"

/**
 * \weakgroup app_widget_group
 *
 * @{
 */

/**
 * \brief Event command ID for the application widgets.
 *
 * \note The command IDs cannot be 0, since this value is reserved for no
 * command event callback for certain widgets.
 */
enum app_widget_ids {
	//! Evvent command ID for the slider.
	SLIDER_ID,
	//! Event command ID for the button to add value.
	BUTTON_ID,
	//! Event command ID for the button to change color.
	BUTTON_2_ID,
};

/**
 * \name Color scheme
 *
 * @{
 */

//! Background color for application
#define APP_BACKGROUND_COLOR        GFX_COLOR(50, 50, 50)
//! Plot draw color alternative one
#define DRAW_COLOR_ONE              GFX_COLOR(100, 100, 255)
//! Plot draw color alternative two
#define DRAW_COLOR_TWO              GFX_COLOR(255, 100, 100)

//! @}

/**
 * \name Widget sizes and positions
 *
 * @{
 */

//! Slider position
#define SLIDER_POS_X                0
//! Slider position
#define SLIDER_POS_Y                220
//! Slider size on display
#define SLIDER_SIZE_X               140
//! Slider size on display
#define SLIDER_SIZE_Y               20

//! Plot position
#define PLOT_POS_X                  0
//! Plot position
#define PLOT_POS_Y                  0
//! Plot size on display
#define PLOT_SIZE_X                 320
//! Plot size on display
#define PLOT_SIZE_Y                 220

//! Button size on display
#define BUTTON_SIZE_X               90
//! Button size on display
#define BUTTON_SIZE_Y               SLIDER_SIZE_Y

//! Spacing from slider to button
#define SLIDER_BUTTON_SPACING_X     0
//! Spacing from button to button
#define BUTTON_BUTTON_SPACING_X     0


//! @}

/**
 * \name Widget configurations
 *
 * @{
 */

//! Max value for slider
#define SLIDER_MAX_VALUE            100

//! @}


/**
 * \name Static variables
 *
 * @{
 */

//! Pointer to frame for application
static struct wtk_basic_frame       *frame;
//! Pointer to slider
static struct wtk_slider            *slider;
//! Pointer to plot
static struct wtk_plot              *plot;
//! Frame background bitmap
static struct gfx_bitmap            frame_background;
//! Plot background bitmap
static struct gfx_bitmap            plot_background;
//! Draw color flag
static bool                         color_change = true;

//! @}

/**
 * \brief Frame command events handler
 *
 * This function handles the command events generated by the widgets.
 * 
 */
static bool widget_frame_command_handler(struct wtk_basic_frame *frame,
		win_command_t command_data)
{
	char command = (char)(uintptr_t)command_data;

	switch (command) {

	// Does nothing
	case SLIDER_ID:
		break;

	// Adds value from slider into the plot and redraws it.
	case BUTTON_ID:
		wtk_plot_add_value(plot,wtk_slider_get_value(slider));
		win_redraw(wtk_plot_as_child(plot));
		break;

	// Changes the draw color of the plot.
	case BUTTON_2_ID:
		if (color_change == true) {
			wtk_plot_set_colors(plot, DRAW_COLOR_ONE,
					&plot_background);
			win_redraw(wtk_plot_as_child(plot));
			color_change = false;
		}
		else {
			wtk_plot_set_colors(plot, DRAW_COLOR_TWO,
					&plot_background);
			win_redraw(wtk_plot_as_child(plot));
			color_change = true;
		}
	}
	return false;
}


/**
 * \brief Setup plot widget demo.
 *
 * This function launches the plot widget demo.
 *
 * \param task Workqueue task used to start the application.
 */
void app_widget_launch(struct workqueue_task *task) {

	struct win_window       *win_root;
	struct win_window       *parent;
	struct win_area         area;
	struct wtk_button       *btn;
	struct wtk_button       *color_btn;

	// Sysfont size.
	sysfont.scale = 1;

	// Get pointer to root window.
	win_root = win_get_root();


	// Application frame

	// Create a background bitmap using a solid color.
	frame_background.type = BITMAP_SOLID;
	frame_background.data.color = APP_BACKGROUND_COLOR;

	// Set the area to fill the entire screen.
	area.pos.x = 0;
	area.pos.y = 0;
	area.size.x = gfx_get_width();
	area.size.y = gfx_get_height();

	/*
	 * Create a basic frame with a specified background and command event
	 * handler. Check the return value if an error occured while creating
	 * the widget.
	 */
	frame = wtk_basic_frame_create(win_root, &area,
			&frame_background, NULL,
			widget_frame_command_handler, NULL);
	if (!frame) {
		goto error_frame;
	}

	// Get a pointer to the widget's window for adding sub-widgets.
	parent = wtk_basic_frame_as_child(frame);
	/*
	 * Draw the frame by showing the frame widget's window. Any
	 * child-widgets and windows will not be shown before the parent
	 * widget/window is shown.
	 */
	win_show(parent);


	// Application slider
	area.pos.x = SLIDER_POS_X;
	area.pos.y = SLIDER_POS_Y;
	area.size.x = SLIDER_SIZE_X;
	area.size.y = SLIDER_SIZE_Y;

	/*
	 * Create the slider and check the return value if an error occured
	 * while creating the slider.
	 */
	slider = wtk_slider_create(parent, &area, SLIDER_MAX_VALUE,
			SLIDER_MAX_VALUE / 2,
			WTK_SLIDER_HORIZONTAL|WTK_SLIDER_CMD_RELEASE,
			SLIDER_ID);
	if (!slider) {
		goto error_widget;
	}

	// Draw the slider by showing the slider widget's window.
	win_show(wtk_slider_as_child(slider));


	// Application plot.
	area.pos.x = PLOT_POS_X;
	area.pos.y = PLOT_POS_Y;
	area.size.x = PLOT_SIZE_X;
	area.size.y = PLOT_SIZE_Y;

	// Create a background bitmap using a solid color.
	plot_background.type = BITMAP_SOLID;
	plot_background.data.color = GFX_COLOR(90,90,90);

	/*
	 * Create the plot widget and check the return value if an error
	 * occured while creating the plot.
	 */
	plot = wtk_plot_create(parent, &area, 100, 33, GFX_COLOR(255, 100, 100),
			&plot_background, WTK_PLOT_LEFT_TO_RIGHT);
	if (!plot) {
		goto error_widget;
	}

	// Set grid/axis options to the plot.
	wtk_plot_set_grid(plot, WTK_PLOT_TICKS_HORIZONTAL |
			WTK_PLOT_TICKS_VERTICAL | WTK_PLOT_ZERO, 40, 0, 20, 50,
			GFX_COLOR(90, 255, 90), GFX_COLOR(0, 0, 100));

	// Draw the plot and by showing the plot widget's window.
	win_show(wtk_plot_as_child(plot));

	/* Values to be plotted when the plot widget starts.
	 * These values will draw a sinus-like graph.
	 */
	wtk_plot_add_value(plot, 50);      //0
	wtk_plot_add_value(plot, 80);      //1
	wtk_plot_add_value(plot, 97);      //2
	wtk_plot_add_value(plot, 97);      //3
	wtk_plot_add_value(plot, 80);      //4
	wtk_plot_add_value(plot, 50);      //5
	wtk_plot_add_value(plot, 20);      //6
	wtk_plot_add_value(plot, 3);       //7
	wtk_plot_add_value(plot, 3);       //8
	wtk_plot_add_value(plot, 20);      //9
	wtk_plot_add_value(plot, 50);      //10
	wtk_plot_add_value(plot, 80);      //11
	wtk_plot_add_value(plot, 97);      //12
	wtk_plot_add_value(plot, 97);      //13
	wtk_plot_add_value(plot, 80);      //14
	wtk_plot_add_value(plot, 50);      //15
	wtk_plot_add_value(plot, 20);      //16
	wtk_plot_add_value(plot, 3);       //17
	wtk_plot_add_value(plot, 3);       //18
	wtk_plot_add_value(plot, 20);      //19
	wtk_plot_add_value(plot, 50);      //20
	wtk_plot_add_value(plot, 80);      //21
	wtk_plot_add_value(plot, 97);      //22
	wtk_plot_add_value(plot, 97);      //23
	wtk_plot_add_value(plot, 80);      //24
	wtk_plot_add_value(plot, 50);      //25
	wtk_plot_add_value(plot, 20);      //26
	wtk_plot_add_value(plot, 3);       //27
	wtk_plot_add_value(plot, 3);       //28
	wtk_plot_add_value(plot, 20);      //29
	wtk_plot_add_value(plot, 50);      //30
	wtk_plot_add_value(plot, 80);      //31
	wtk_plot_add_value(plot, 97);      //32

	win_redraw(wtk_plot_as_child(plot));


	// Application add value button.
	area.pos.x = SLIDER_POS_X + SLIDER_SIZE_X + SLIDER_BUTTON_SPACING_X
			+ BUTTON_BUTTON_SPACING_X;
	area.pos.y = SLIDER_POS_Y;
	area.size.x = BUTTON_SIZE_X;
	area.size.y = BUTTON_SIZE_Y;

	/*
	 * Create the button and check the return value if an error
	 * occured while creating the button.
	 */
	btn = wtk_button_create(parent, &area, "Add value",
	(win_command_t)BUTTON_ID);
	if (!btn) {
		goto error_widget;
	}

	// Draw the button by showing the button widget's window.
	win_show(wtk_button_as_child(btn));


	// Application color button.
	area.pos.x = SLIDER_POS_X + SLIDER_SIZE_X + SLIDER_BUTTON_SPACING_X
			+ BUTTON_BUTTON_SPACING_X + BUTTON_SIZE_X;
	area.pos.y = SLIDER_POS_Y;
	area.size.x = BUTTON_SIZE_X;
	area.size.y = 20;

	/*
	 * Create the button and check the return value if an error
	 * occured while creating the button.
	 */
	color_btn = wtk_button_create(parent, &area, "Change color",
	(win_command_t)BUTTON_2_ID);
	if (!btn) {
		goto error_widget;
	}

	// Draw the button by showing the button widget's window.
	win_show(wtk_button_as_child(color_btn));

	return;

error_widget:
	// Destroy widget and all sub-widgets.
	win_destroy(wtk_basic_frame_as_child(frame));
error_frame:
	// Wait forever if an error occured during setup.
	while(1);
}

//! @}
