include $(src)/cpu/uc3/config.mk

CONFIG_CHIP_AT32UC3A3=y
CONFIG_CHIP_HAS_HSB_SRAM=y
CONFIG_PORTMUX_GPIO=y
CONFIG_AVR32_PM_V2=y

CONFIG_SYSCLK_SOURCE=SYSCLK_SRC_OSC0
CONFIG_SYSCLK_CPU_DIV=0
CONFIG_SYSCLK_PBA_DIV=0

CONFIG_HAVE_GENCLK=y
CONFIG_HAVE_HSB=y
CONFIG_HAVE_OSC=y
CONFIG_HAVE_PLL=y
CONFIG_HAVE_TC=y

config_mk		+= $(src)/chip/at32uc3a3/config.mk
platform-mkfiles	+= $(src)/chip/at32uc3a3/chip.mk
