include $(src)/cpu/mega/config.mk

CONFIG_AVR_ARCH=5
CONFIG_AVR_CORE=3
CONFIG_CHIP_AT90USB1287=y
CONFIG_MEMORY_MODEL_SMALL=y
CONFIG_NR_IRQS=38
CONFIG_FLASH_BASE=0
CONFIG_HAVE_GPIO_PORTA=y
CONFIG_HAVE_GPIO_PORTB=y
CONFIG_HAVE_GPIO_PORTC=y
CONFIG_HAVE_GPIO_PORTD=y
CONFIG_HAVE_GPIO_PORTE=y
CONFIG_HAVE_GPIO_PORTF=y

CONFIG_FLASH_NEND=0xFFFF
CONFIG_FLASH_END=0x21FFF
CONFIG_SRAM_BASE=0x100
CONFIG_SRAM_TBASE=0x0
CONFIG_SRAM_TSIZE=0x0
CONFIG_SRAM_END=0x20FF
CONFIG_EEPROM_END=0x7FF
CONFIG_EEPROM_START=0x0
CONFIG_EEPROM_SIZE=0x800

config_mk		+= $(src)/chip/at90usb1287/config.mk
platform-mkfiles	+= $(src)/chip/at90usb1287/chip.mk
