CONFIG_MAINLOOP=y

CONFIG_PHYSMEM=y
CONFIG_MEMPOOL=y
CONFIG_MEMBAG=y
CONFIG_BUFFER=y
CONFIG_NR_BUFFERS=2

CONFIG_GFX=y
CONFIG_GFX_USE_CLIPPING=y
CONFIG_GFX_HX8347A=y
CONFIG_GFX_WIN=y
CONFIG_GFX_WTK=y
CONFIG_GFX_SYSFONT=y

CONFIG_STREAM=y

CONFIG_TIMER=y
CONFIG_TIMER_0=y
CONFIG_TIMER_ID=0
CONFIG_TIMER_RESOLUTION=1000

config_mk	+= $(appsrc)/config.mk
