include $(src)/board/atevk1104/config.mk
include $(src)/apps/display-demo/config.mk

CONFIG_PLL0_SOURCE=PLL_SRC_OSC0
CONFIG_PLL0_MUL=5
CONFIG_PLL0_DIV=1
CONFIG_SYSCLK_SOURCE=SYSCLK_SRC_PLL0

# Debug console stuff
CONFIG_ASSERT=y
CONFIG_STREAM=y
CONFIG_SERIAL_UART=y
CONFIG_UART_BAUD_RATE=115200
CONFIG_DEBUG_CONSOLE=y
CONFIG_DEBUG_UART=y
CONFIG_DEBUG_UART_ID=1
#CONFIG_DEBUG_LEVEL=DEBUG_VERBOSE
