/**
 * \file
 *
 * \brief Dialogue box widget application
 *
 * Copyright (C) 2009 Atmel Corporation. All rights reserved.
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 * Atmel AVR product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#include <led.h>
#include <board.h>
#include <string.h>

#include <gfx/gfx.h>
#include <gfx/win.h>
#include <gfx/wtk.h>
#include <gfx/sysfont.h>
#include <membag.h>
#include <debug.h>
#include <mainloop.h>
#include <string.h>
#include <stream.h>

#include "app_dialogue.h"

/**
 * \weakgroup app_widget_group
 *
 * @{
 */

/**
 * \brief Event command ID for the application widgets.
 *
 * \note The command IDs cannot be 0, since this value is reserved for no
 * command event callback for certain widgets.
 */
enum app_widget_ids {

	//! Event command ID for the button.
	BUTTON_ID = 1,
	//! Event command ID for the dialogue box.
	DIALOGUE_ID,
};

/**
 * \name Color scheme
 *
 * @{
 */

//! Background color for application
#define APP_BACKGROUND_COLOR        GFX_COLOR(50, 50, 50)

//! @}

/**
 * \name Widget sizes and positions
 *
 * @{
 */

//! Label position on top of display
#define LABEL_POS_X                 10
//! Label position on top of display
#define LABEL_POS_Y                 10


//! @}

/**
 * \name Widget configurations
 *
 * @{
 */


//! @}

/**
 * \name Static text strings
 *
 * @{
 */

//! Description for label
const static char                   *demo_string = "Dialogue box widget demomonstration";

//! @}

/**
 * \name Static variables
 *
 * @{
 */

//! Pointer to frame for dialogue_box
static struct win_window            *dialogue_box;
//! Pointer to frame for application
static struct wtk_basic_frame       *frame;
//! Frame background bitmap
static struct gfx_bitmap            frame_background;
//! Counter for button
static uint8_t                      counter;
//! Pointer to the sub-frame
static struct wtk_basic_frame       *sub_frame;
//! Sub-frame background bitmap
static struct gfx_bitmap            sub_frame_background;

//! @}


/**
 * \brief Frame command events handler
 *
 * This function handles the command events generated by the widgets.
 *
 * \sa wtk_basic_frame_command_handler_t
 */
static bool widget_frame_command_handler(struct wtk_basic_frame *frame,
		win_command_t command_data)
{
	char command = (char)(uintptr_t)command_data;

	char *caption = "Dialogue box demo:";

	char *second_caption = "Click 'OK' to increase counter";

	struct win_window       *parent;

	parent = wtk_basic_frame_as_child(frame);

	switch (command) {

	case BUTTON_ID:

		// Changes the caption if counter is changed
		switch (counter) {
			case 1:
				second_caption = "Click 'OK' once more"; break;
			case 2:
				second_caption = "Click 'OK' once again"; break;
			case 3:
				second_caption = "Click 'OK' one more time"; break;
			case 4:
				second_caption = "Click 'OK' once upon a time"; break;
			case 5:
				second_caption = "Click 'OK' at once"; break;
			case 6:
				second_caption = "Click 'OK' until you cant stop"; break;
			case 7:
				second_caption = "Click 'OK' if you need help"; break;
			case 8:
				second_caption = "Click 'OK' for more information"; break;
			case 9:
				second_caption = "Click 'OK' twice"; break;
			case 20:
				second_caption = "Giving up?"; break;
			case 50:
				second_caption = "Please stop clicking!"; break;
			case 51:
				second_caption = "Your causing wear on the screen!"; break;
			default:
				second_caption = "Click 'OK' to increase counter"; break;

		}

		/**
		 * Create the dialogue_box with its custom captions
		 *
		 *
		 */
		
		dialogue_box = wtk_dialogue_box_create(parent, caption, second_caption,
				(win_command_t)DIALOGUE_ID);
		break;

	case DIALOGUE_ID:
		counter++;
		win_redraw(wtk_basic_frame_as_child(sub_frame));

	}

	return false;
}

/**
 * \brief Frame draw event handler
 *
 * This function will draw the contents of the sub-frame.
 *
 * \sa wtk_basic_frame_draw_handler_t
 */
static void sub_frame_draw_handler(struct win_window *win,
		struct win_clip_region const *clip)
{
	char buffer[4];

	snprintf(buffer, sizeof(buffer), "%3d", counter);
	/**
	 * \todo Add code here to draw text on screen using the
	 * gfx_draw_string() function.
	 */
	gfx_draw_string(buffer, clip->origin.x + 30, clip->origin.y + 12,
			&sysfont, GFX_COLOR(255, 255, 255),
			GFX_COLOR_TRANSPARENT);
}

/**
 * \brief Setup widget demo
 *
 * This function launches the widget demo.
 *
 * \param task Workqueue task used to start the application.
 */
void app_widget_launch(struct workqueue_task *task) {

	struct win_window       *win_root;
	struct win_window       *parent;
	struct wtk_label        *lbl;
	struct wtk_button       *btn;
	struct win_area         area;

	// Use regular sysfont for this app
	sysfont.scale = 1;

	// Get pointer to root window
	win_root = win_get_root();


	// Create a background bitmap using a solid color.
	frame_background.type = BITMAP_SOLID;
	frame_background.data.color = APP_BACKGROUND_COLOR;

	// Set the area to fill the entire screen
	area.pos.x = 0;
	area.pos.y = 0;
	area.size.x = gfx_get_width();
	area.size.y = gfx_get_height();

	/*
	 * Create a basic frame with a specified background and command event
	 * handler. Check the return value if an error occured while creating
	 * the widget.
	 */
	frame = wtk_basic_frame_create(win_root, &area,
			&frame_background, NULL,
			widget_frame_command_handler, NULL);
	if (!frame) {
		goto error_frame;
	}


	// Get a pointer to the widget's window for adding sub-widgets.
	parent = wtk_basic_frame_as_child(frame);
	/*
	 * Draw the frame by showing the frame widget's window. Any
	 * child-widgets and windows will not be shown before the parent
	 * widget/window is shown.
	 */
	win_show(parent);


	// Application label
	area.pos.x = LABEL_POS_X;
	area.pos.y = LABEL_POS_Y;
	// Find an optimal size for the widget.
	wtk_label_size_hint(&area.size, demo_string);

	/*
	 * Create the label and check the return value if an error occured
	 * while creating the label.
	 */
	lbl = wtk_label_create(parent, &area, demo_string, false);
	if (!lbl) {
		goto error_widget;
	}

	// Draw the label by showing the label widget's window.
	win_show(wtk_label_as_child(lbl));


	area.pos.x =  60;
	area.pos.y = 190;
	area.size.x = 90;
	area.size.y = 40;

	btn = wtk_button_create(parent, &area, "Open dialogue",
			(win_command_t)BUTTON_ID);
	if (!btn) {
		goto error_widget;
	}
	win_show(wtk_button_as_child(btn));


	area.pos.x += area.size.x + 20;

	sub_frame_background.type = BITMAP_SOLID;
	sub_frame_background.data.color = GFX_COLOR(127, 0, 0);

	sub_frame = wtk_basic_frame_create(parent, &area,
			&sub_frame_background, sub_frame_draw_handler,
			NULL, NULL);
	if (!sub_frame) {
		goto error_widget;
	}
	win_show(wtk_basic_frame_as_child(sub_frame));


	return;

error_widget:
	// Destroy widget and all sub-widgets.
	win_destroy(wtk_basic_frame_as_child(frame));
error_frame:
	// Wait forever if an error occured during setup.
	while(1);
}

//! @}
