CONFIG_MAINLOOP=y

CONFIG_PHYSMEM=y
CONFIG_MEMPOOL=y
CONFIG_MEMBAG=y
CONFIG_MALLOC_SIMPLE=y

CONFIG_BUFFER=y
CONFIG_NR_BUFFERS=2

CONFIG_GFX=y
CONFIG_GFX_USE_CLIPPING=y
CONFIG_GFX_HX8347A=y
CONFIG_GFX_WIN=y
CONFIG_GFX_WTK=y
CONFIG_GFX_SYSFONT=y

CONFIG_STREAM=y

config_mk	+= $(appsrc)/config.mk
